#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
#ifndef RUNTIMEKIT_SWIFT_H
#define RUNTIMEKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AssetKit;
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#import <RuntimeKit/RuntimeKit.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="RuntimeKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSURL;

@interface AssetManager (SWIFT_EXTENSION(RuntimeKit))
- (void)addShaderBundleAssetPackWithUrl:(NSURL * _Nonnull)url;
@end


SWIFT_CLASS("_TtC10RuntimeKit12AudioManager")
@interface AudioManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AudioManager * _Nonnull shared;)
+ (AudioManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly) double micAmplitude;
@property (nonatomic, readonly) double micFrequency;
- (void)startMicTracker;
- (void)stopMicTracker;
@end

@class ThreadedRuntimeViewController;
@class NSCoder;
@class NSString;
@class NSBundle;

SWIFT_CLASS("_TtC10RuntimeKit19CodeaViewController")
@interface CodeaViewController : UIViewController <ThreadedRuntimeViewControllerDelegate>
@property (nonatomic, readonly, strong) ThreadedRuntimeViewController * _Nonnull runtime;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)runtimeViewControllerDidFinishSetup:(id _Nonnull)context;
- (void)runtimeViewController:(id _Nonnull)context willPause:(BOOL)pause;
- (void)runtimeViewControllerDidRestart:(id _Nonnull)context;
@property (nonatomic) BOOL prefersPointerLocked;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end



@interface CodeaViewController (SWIFT_EXTENSION(RuntimeKit))
@property (nonatomic, readonly) BOOL isStandaloneEditor;
- (void)closeScene;
- (void)configureUserActivity;
@end


@class CodeaLuaState;

@interface CodeaViewController (SWIFT_EXTENSION(RuntimeKit)) <CodeaLuaStateDelegate>
- (void)luaStateCreated:(CodeaLuaState * _Null_unspecified)state isValidating:(BOOL)validating;
- (void)luaState:(CodeaLuaState * _Null_unspecified)state printedText:(NSString * _Null_unspecified)text;
- (void)luaState:(CodeaLuaState * _Null_unspecified)state tracedText:(NSString * _Null_unspecified)text;
- (void)luaState:(CodeaLuaState * _Null_unspecified)state warningText:(NSString * _Null_unspecified)text;
- (void)luaState:(CodeaLuaState * _Null_unspecified)state errorOccured:(NSString * _Null_unspecified)error;
- (void)clearOutputForCodeaLuaState:(CodeaLuaState * _Null_unspecified)state;
- (void)removeAllParametersForCodeaLuaState:(CodeaLuaState * _Null_unspecified)state;
- (void)luaState:(CodeaLuaState * _Null_unspecified)state registerWatch:(NSString * _Null_unspecified)expression;
- (void)luaState:(CodeaLuaState * _Null_unspecified)state registerFloatParameter:(NSString * _Null_unspecified)name initialValue:(CGFloat)value withMin:(CGFloat)minVal andMax:(CGFloat)maxVal callback:(int32_t)callback;
- (void)luaState:(CodeaLuaState * _Null_unspecified)state registerIntegerParameter:(NSString * _Null_unspecified)name initialValue:(NSInteger)value withMin:(NSInteger)minVal andMax:(NSInteger)maxVal callback:(int32_t)callback;
- (void)luaState:(CodeaLuaState * _Null_unspecified)state registerColorParameter:(NSString * _Null_unspecified)name initialRed:(CGFloat)red initialGreen:(CGFloat)green initialBlue:(CGFloat)blue initialAlpha:(CGFloat)alpha callback:(int32_t)callback;
- (void)luaState:(CodeaLuaState * _Null_unspecified)state registerBoolParameter:(NSString * _Null_unspecified)name initialValue:(BOOL)initial callback:(int32_t)callback;
- (void)luaState:(CodeaLuaState * _Null_unspecified)state registerTextParameter:(NSString * _Null_unspecified)name initialValue:(NSString * _Null_unspecified)initial callback:(int32_t)callback;
- (void)luaState:(CodeaLuaState * _Null_unspecified)state registerActionParameter:(NSString * _Null_unspecified)name callback:(int32_t)callback;
- (void)luaStateUpdatedParameters:(CodeaLuaState * _Null_unspecified)state;
- (void)luaStateWillClose:(CodeaLuaState * _Null_unspecified)state;
@end

@class NSMutableDictionary;

SWIFT_CLASS("_TtC10RuntimeKit17ExternalAssetPack")
@interface ExternalAssetPack : AssetPack
@property (nonatomic, strong) NSMutableDictionary * _Nonnull info;
@property (nonatomic) BOOL userPack;
@property (nonatomic, readonly, copy) NSString * _Nonnull resolvedPath;
@property (nonatomic) BOOL allowImportAll;
@property (nonatomic, copy) NSString * _Nullable path;
@property (nonatomic, readonly, copy) NSURL * _Nullable bookmarkedUrl;
- (AssetPack * _Nonnull)childAssetPackAtPath:(NSString * _Nonnull)path SWIFT_WARN_UNUSED_RESULT;
- (void)createFolder:(NSString * _Nonnull)folderName;
- (void)writeAsset:(NSString * _Nonnull)fileName writer:(AssetPackWriter _Nonnull)writer;
- (void)reloadFilesFromBundlePath;
- (BOOL)startAccessingSecurityScopedResource SWIFT_WARN_UNUSED_RESULT;
- (void)stopAccessingSecurityScopedResource;
- (nonnull instancetype)initWithPath:(NSString * _Nonnull)path validFileTypes:(NSArray * _Nullable)validExt SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface NSNotification (SWIFT_EXTENSION(RuntimeKit))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull projectManagerDidCopyExamplesNotification;)
+ (NSString * _Nonnull)projectManagerDidCopyExamplesNotification SWIFT_WARN_UNUSED_RESULT;
@end

@class OSCMessage;

SWIFT_CLASS("_TtC10RuntimeKit10OSCManager")
@interface OSCManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) OSCManager * _Nonnull shared;)
+ (OSCManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) NSString * _Nonnull host;
@property (nonatomic) NSInteger port;
@property (nonatomic, copy) void (^ _Nonnull messageHandler)(OSCMessage * _Nonnull);
- (void)startServerWithPort:(NSInteger)port completion:(SWIFT_NOESCAPE void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completion;
- (void)stopServer;
- (void)sendMessage:(NSString * _Nonnull)address contents:(NSArray * _Nonnull)contents;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end





@interface Project (SWIFT_EXTENSION(RuntimeKit))
- (void)fixDependencies;
@end

@protocol ProjectCollectionDelegate;
enum ProjectCollectionSorting : NSInteger;

/// Monitors a directory on the system and maintains a list
/// of Codea projects in that directory
SWIFT_RESILIENT_CLASS("_TtC10RuntimeKit17ProjectCollection")
@interface ProjectCollection : DirectoryMonitor
/// The delegate will get callbacks relating to project
/// deletion, insertion and modification
/// Setting a delegate suppresses notifications through
/// NotificationCenter
@property (nonatomic, weak) id <ProjectCollectionDelegate> _Nullable delegate;
- (nonnull instancetype)initWithUrl:(NSURL * _Nullable)url monitorForUpdates:(BOOL)monitorForUpdates OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
- (BOOL)deleteProject:(Project * _Nonnull)project SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasProject:(Project * _Nonnull)project SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasProjectWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
- (Project * _Nullable)projectWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSInteger count;
@property (nonatomic) enum ProjectCollectionSorting sortOrder;
@property (nonatomic, readonly, copy) NSArray<Project *> * _Nonnull sortedProjects;
- (nonnull instancetype)initWithUrl:(NSURL * _Nullable)url monitorForUpdates:(BOOL)monitorForUpdates skipHiddenFiles:(BOOL)skipHiddenFiles SWIFT_UNAVAILABLE;
@end


SWIFT_PROTOCOL("_TtP10RuntimeKit25ProjectCollectionDelegate_")
@protocol ProjectCollectionDelegate <NSObject>
- (void)projectCollection:(ProjectCollection * _Nonnull)collection removedProject:(Project * _Nonnull)project at:(NSInteger)index;
- (void)projectCollection:(ProjectCollection * _Nonnull)collection insertedProject:(Project * _Nonnull)project at:(NSInteger)index;
- (void)projectCollection:(ProjectCollection * _Nonnull)collection modifiedProject:(Project * _Nonnull)project at:(NSInteger)index;
- (void)reloadProjectCollection:(ProjectCollection * _Nonnull)collection;
@end

@class ProjectRepository;
@class NSIndexPath;

SWIFT_PROTOCOL("_TtP10RuntimeKit35ProjectCollectionRepositoryDelegate_")
@protocol ProjectCollectionRepositoryDelegate
- (void)repository:(ProjectRepository * _Nonnull)repository didInsertProject:(Project * _Nonnull)project at:(NSIndexPath * _Nonnull)indexPath;
- (void)repository:(ProjectRepository * _Nonnull)repository didRemoveProject:(Project * _Nonnull)project at:(NSIndexPath * _Nonnull)indexPath;
- (void)repository:(ProjectRepository * _Nonnull)repository didModifyProject:(Project * _Nonnull)project at:(NSIndexPath * _Nonnull)indexPath;
- (void)repository:(ProjectRepository * _Nonnull)repository didInsertCollectionAtIndex:(NSInteger)index;
- (void)repository:(ProjectRepository * _Nonnull)repository didRemoveCollectionAtIndex:(NSInteger)index;
- (void)repository:(ProjectRepository * _Nonnull)repository reloadedCollectionAtIndex:(NSInteger)index;
- (void)repositoryDidReload:(ProjectRepository * _Nonnull)repository;
@end

typedef SWIFT_ENUM(NSInteger, ProjectCollectionSorting, open) {
  ProjectCollectionSortingDate = 0,
  ProjectCollectionSortingName = 1,
  ProjectCollectionSortingOrdered = 2,
};


SWIFT_CLASS("_TtC10RuntimeKit14ProjectManager")
@interface ProjectManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ProjectManager * _Nonnull shared;)
+ (ProjectManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull defaultProjectCollectionName;)
+ (NSString * _Nonnull)defaultProjectCollectionName SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, strong) ProjectRepository * _Nonnull local;
@property (nonatomic, strong) ProjectRepository * _Nonnull iCloud;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (Project * _Nullable)projectWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasProjectWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
- (ProjectCollection * _Nullable)collectionWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
- (ProjectCollection * _Nullable)collectionForProject:(Project * _Nonnull)project SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, strong) Project * _Nonnull defaultProjectTemplate;
@property (nonatomic, readonly, copy) NSArray<Project *> * _Nonnull templateProjects;
- (BOOL)saveProject:(Project * _Nonnull)project SWIFT_WARN_UNUSED_RESULT;
- (void)embedDependenciesIntoProject:(Project * _Nonnull)project;
@end


@interface ProjectManager (SWIFT_EXTENSION(RuntimeKit))
- (void)createCollectionWithName:(NSString * _Nonnull)name completion:(void (^ _Nonnull)(ProjectCollection * _Nullable, NSError * _Nullable))completion;
@end

@class UIColor;

@interface ProjectManager (SWIFT_EXTENSION(RuntimeKit))
+ (void)createProjectWithName:(NSString * _Nonnull)name withProjectString:(NSString * _Nonnull)projectString in:(ProjectCollection * _Nonnull)collection tintColor:(UIColor * _Nullable)tintColor completion:(void (^ _Nonnull)(Project * _Nullable, NSError * _Nullable))completion;
+ (void)createProjectWithName:(NSString * _Nonnull)name withTemplate:(Project * _Nonnull)template_ in:(ProjectCollection * _Nonnull)collection tintColor:(UIColor * _Nullable)tintColor completion:(void (^ _Nonnull)(Project * _Nullable, NSError * _Nullable))completion;
@end



@interface ProjectManager (SWIFT_EXTENSION(RuntimeKit))
- (NSArray<Project *> * _Nonnull)sortedDependentProjectsForProject:(Project * _Nonnull)project shouldFix:(BOOL)fix SWIFT_WARN_UNUSED_RESULT;
- (NSSet<Project *> * _Nonnull)allDependentProjectsForProject:(Project * _Nonnull)project shouldFix:(BOOL)fix SWIFT_WARN_UNUSED_RESULT;
- (NSSet<Project *> * _Nonnull)allDependentProjectsForProject:(Project * _Nonnull)project shouldFix:(BOOL)fix dependencies:(NSSet<Project *> * _Nonnull)dependencies SWIFT_WARN_UNUSED_RESULT;
@end


/// Monitors a local directory on the file system and creates
/// project collections for each subdirectory
/// This also creates a project collection representing the top-
/// level directory
SWIFT_RESILIENT_CLASS("_TtC10RuntimeKit17ProjectRepository")
@interface ProjectRepository : DirectoryMonitor <ProjectCollectionDelegate>
@property (nonatomic, readonly, copy) NSArray<ProjectCollection *> * _Nonnull collections;
- (void)projectCollection:(ProjectCollection * _Nonnull)collection removedProject:(Project * _Nonnull)project at:(NSInteger)index;
- (void)projectCollection:(ProjectCollection * _Nonnull)collection insertedProject:(Project * _Nonnull)project at:(NSInteger)index;
- (void)projectCollection:(ProjectCollection * _Nonnull)collection modifiedProject:(Project * _Nonnull)project at:(NSInteger)index;
- (void)reloadProjectCollection:(ProjectCollection * _Nonnull)collection;
- (nonnull instancetype)initWithUrl:(NSURL * _Nullable)url monitorForUpdates:(BOOL)monitorForUpdates skipHiddenFiles:(BOOL)skipHiddenFiles OBJC_DESIGNATED_INITIALIZER;
@end


@class UIFont;

SWIFT_CLASS("_TtC10RuntimeKit12RuntimeStyle")
@interface RuntimeStyle : NSObject
+ (UIFont * _Nonnull)codeFontWithSize:(CGFloat)size weight:(UIFontWeight)weight SWIFT_WARN_UNUSED_RESULT;
+ (UIFont * _Nonnull)codeFontForTextStyle:(UIFontTextStyle _Nonnull)textStyle weight:(UIFontWeight)weight SWIFT_WARN_UNUSED_RESULT;
+ (UIFont * _Nonnull)defaultFontWithSize:(CGFloat)size weight:(UIFontWeight)weight SWIFT_WARN_UNUSED_RESULT;
+ (UIFont * _Nonnull)preferredFontForTextStyle:(UIFontTextStyle _Nonnull)textStyle weight:(UIFontWeight)weight SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIFont * _Nonnull sidebarTitleFont;)
+ (UIFont * _Nonnull)sidebarTitleFont SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIFont * _Nonnull parameterTitleFont;)
+ (UIFont * _Nonnull)parameterTitleFont SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIFont * _Nonnull parameterValueFont;)
+ (UIFont * _Nonnull)parameterValueFont SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIFont * _Nonnull parameterActionFont;)
+ (UIFont * _Nonnull)parameterActionFont SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIFont * _Nonnull parameterTextFont;)
+ (UIFont * _Nonnull)parameterTextFont SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIFont * _Nonnull capturePanelTitleFont;)
+ (UIFont * _Nonnull)capturePanelTitleFont SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIApplication (SWIFT_EXTENSION(RuntimeKit))
- (UIViewController * _Nullable)viewControllerFor:(CodeaLuaState * _Nonnull)luaState SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC10RuntimeKit11WifiAddress")
@interface WifiAddress : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable current;)
+ (NSString * _Nullable)current SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
#ifndef RUNTIMEKIT_SWIFT_H
#define RUNTIMEKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AssetKit;
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#import <RuntimeKit/RuntimeKit.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="RuntimeKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSURL;

@interface AssetManager (SWIFT_EXTENSION(RuntimeKit))
- (void)addShaderBundleAssetPackWithUrl:(NSURL * _Nonnull)url;
@end


SWIFT_CLASS("_TtC10RuntimeKit12AudioManager")
@interface AudioManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AudioManager * _Nonnull shared;)
+ (AudioManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly) double micAmplitude;
@property (nonatomic, readonly) double micFrequency;
- (void)startMicTracker;
- (void)stopMicTracker;
@end

@class ThreadedRuntimeViewController;
@class NSCoder;
@class NSString;
@class NSBundle;

SWIFT_CLASS("_TtC10RuntimeKit19CodeaViewController")
@interface CodeaViewController : UIViewController <ThreadedRuntimeViewControllerDelegate>
@property (nonatomic, readonly, strong) ThreadedRuntimeViewController * _Nonnull runtime;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)runtimeViewControllerDidFinishSetup:(id _Nonnull)context;
- (void)runtimeViewController:(id _Nonnull)context willPause:(BOOL)pause;
- (void)runtimeViewControllerDidRestart:(id _Nonnull)context;
@property (nonatomic) BOOL prefersPointerLocked;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end



@interface CodeaViewController (SWIFT_EXTENSION(RuntimeKit))
@property (nonatomic, readonly) BOOL isStandaloneEditor;
- (void)closeScene;
- (void)configureUserActivity;
@end


@class CodeaLuaState;

@interface CodeaViewController (SWIFT_EXTENSION(RuntimeKit)) <CodeaLuaStateDelegate>
- (void)luaStateCreated:(CodeaLuaState * _Null_unspecified)state isValidating:(BOOL)validating;
- (void)luaState:(CodeaLuaState * _Null_unspecified)state printedText:(NSString * _Null_unspecified)text;
- (void)luaState:(CodeaLuaState * _Null_unspecified)state tracedText:(NSString * _Null_unspecified)text;
- (void)luaState:(CodeaLuaState * _Null_unspecified)state warningText:(NSString * _Null_unspecified)text;
- (void)luaState:(CodeaLuaState * _Null_unspecified)state errorOccured:(NSString * _Null_unspecified)error;
- (void)clearOutputForCodeaLuaState:(CodeaLuaState * _Null_unspecified)state;
- (void)removeAllParametersForCodeaLuaState:(CodeaLuaState * _Null_unspecified)state;
- (void)luaState:(CodeaLuaState * _Null_unspecified)state registerWatch:(NSString * _Null_unspecified)expression;
- (void)luaState:(CodeaLuaState * _Null_unspecified)state registerFloatParameter:(NSString * _Null_unspecified)name initialValue:(CGFloat)value withMin:(CGFloat)minVal andMax:(CGFloat)maxVal callback:(int32_t)callback;
- (void)luaState:(CodeaLuaState * _Null_unspecified)state registerIntegerParameter:(NSString * _Null_unspecified)name initialValue:(NSInteger)value withMin:(NSInteger)minVal andMax:(NSInteger)maxVal callback:(int32_t)callback;
- (void)luaState:(CodeaLuaState * _Null_unspecified)state registerColorParameter:(NSString * _Null_unspecified)name initialRed:(CGFloat)red initialGreen:(CGFloat)green initialBlue:(CGFloat)blue initialAlpha:(CGFloat)alpha callback:(int32_t)callback;
- (void)luaState:(CodeaLuaState * _Null_unspecified)state registerBoolParameter:(NSString * _Null_unspecified)name initialValue:(BOOL)initial callback:(int32_t)callback;
- (void)luaState:(CodeaLuaState * _Null_unspecified)state registerTextParameter:(NSString * _Null_unspecified)name initialValue:(NSString * _Null_unspecified)initial callback:(int32_t)callback;
- (void)luaState:(CodeaLuaState * _Null_unspecified)state registerActionParameter:(NSString * _Null_unspecified)name callback:(int32_t)callback;
- (void)luaStateUpdatedParameters:(CodeaLuaState * _Null_unspecified)state;
- (void)luaStateWillClose:(CodeaLuaState * _Null_unspecified)state;
@end

@class NSMutableDictionary;

SWIFT_CLASS("_TtC10RuntimeKit17ExternalAssetPack")
@interface ExternalAssetPack : AssetPack
@property (nonatomic, strong) NSMutableDictionary * _Nonnull info;
@property (nonatomic) BOOL userPack;
@property (nonatomic, readonly, copy) NSString * _Nonnull resolvedPath;
@property (nonatomic) BOOL allowImportAll;
@property (nonatomic, copy) NSString * _Nullable path;
@property (nonatomic, readonly, copy) NSURL * _Nullable bookmarkedUrl;
- (AssetPack * _Nonnull)childAssetPackAtPath:(NSString * _Nonnull)path SWIFT_WARN_UNUSED_RESULT;
- (void)createFolder:(NSString * _Nonnull)folderName;
- (void)writeAsset:(NSString * _Nonnull)fileName writer:(AssetPackWriter _Nonnull)writer;
- (void)reloadFilesFromBundlePath;
- (BOOL)startAccessingSecurityScopedResource SWIFT_WARN_UNUSED_RESULT;
- (void)stopAccessingSecurityScopedResource;
- (nonnull instancetype)initWithPath:(NSString * _Nonnull)path validFileTypes:(NSArray * _Nullable)validExt SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface NSNotification (SWIFT_EXTENSION(RuntimeKit))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull projectManagerDidCopyExamplesNotification;)
+ (NSString * _Nonnull)projectManagerDidCopyExamplesNotification SWIFT_WARN_UNUSED_RESULT;
@end

@class OSCMessage;

SWIFT_CLASS("_TtC10RuntimeKit10OSCManager")
@interface OSCManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) OSCManager * _Nonnull shared;)
+ (OSCManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) NSString * _Nonnull host;
@property (nonatomic) NSInteger port;
@property (nonatomic, copy) void (^ _Nonnull messageHandler)(OSCMessage * _Nonnull);
- (void)startServerWithPort:(NSInteger)port completion:(SWIFT_NOESCAPE void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completion;
- (void)stopServer;
- (void)sendMessage:(NSString * _Nonnull)address contents:(NSArray * _Nonnull)contents;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end





@interface Project (SWIFT_EXTENSION(RuntimeKit))
- (void)fixDependencies;
@end

@protocol ProjectCollectionDelegate;
enum ProjectCollectionSorting : NSInteger;

/// Monitors a directory on the system and maintains a list
/// of Codea projects in that directory
SWIFT_RESILIENT_CLASS("_TtC10RuntimeKit17ProjectCollection")
@interface ProjectCollection : DirectoryMonitor
/// The delegate will get callbacks relating to project
/// deletion, insertion and modification
/// Setting a delegate suppresses notifications through
/// NotificationCenter
@property (nonatomic, weak) id <ProjectCollectionDelegate> _Nullable delegate;
- (nonnull instancetype)initWithUrl:(NSURL * _Nullable)url monitorForUpdates:(BOOL)monitorForUpdates OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
- (BOOL)deleteProject:(Project * _Nonnull)project SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasProject:(Project * _Nonnull)project SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasProjectWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
- (Project * _Nullable)projectWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSInteger count;
@property (nonatomic) enum ProjectCollectionSorting sortOrder;
@property (nonatomic, readonly, copy) NSArray<Project *> * _Nonnull sortedProjects;
- (nonnull instancetype)initWithUrl:(NSURL * _Nullable)url monitorForUpdates:(BOOL)monitorForUpdates skipHiddenFiles:(BOOL)skipHiddenFiles SWIFT_UNAVAILABLE;
@end


SWIFT_PROTOCOL("_TtP10RuntimeKit25ProjectCollectionDelegate_")
@protocol ProjectCollectionDelegate <NSObject>
- (void)projectCollection:(ProjectCollection * _Nonnull)collection removedProject:(Project * _Nonnull)project at:(NSInteger)index;
- (void)projectCollection:(ProjectCollection * _Nonnull)collection insertedProject:(Project * _Nonnull)project at:(NSInteger)index;
- (void)projectCollection:(ProjectCollection * _Nonnull)collection modifiedProject:(Project * _Nonnull)project at:(NSInteger)index;
- (void)reloadProjectCollection:(ProjectCollection * _Nonnull)collection;
@end

@class ProjectRepository;
@class NSIndexPath;

SWIFT_PROTOCOL("_TtP10RuntimeKit35ProjectCollectionRepositoryDelegate_")
@protocol ProjectCollectionRepositoryDelegate
- (void)repository:(ProjectRepository * _Nonnull)repository didInsertProject:(Project * _Nonnull)project at:(NSIndexPath * _Nonnull)indexPath;
- (void)repository:(ProjectRepository * _Nonnull)repository didRemoveProject:(Project * _Nonnull)project at:(NSIndexPath * _Nonnull)indexPath;
- (void)repository:(ProjectRepository * _Nonnull)repository didModifyProject:(Project * _Nonnull)project at:(NSIndexPath * _Nonnull)indexPath;
- (void)repository:(ProjectRepository * _Nonnull)repository didInsertCollectionAtIndex:(NSInteger)index;
- (void)repository:(ProjectRepository * _Nonnull)repository didRemoveCollectionAtIndex:(NSInteger)index;
- (void)repository:(ProjectRepository * _Nonnull)repository reloadedCollectionAtIndex:(NSInteger)index;
- (void)repositoryDidReload:(ProjectRepository * _Nonnull)repository;
@end

typedef SWIFT_ENUM(NSInteger, ProjectCollectionSorting, open) {
  ProjectCollectionSortingDate = 0,
  ProjectCollectionSortingName = 1,
  ProjectCollectionSortingOrdered = 2,
};


SWIFT_CLASS("_TtC10RuntimeKit14ProjectManager")
@interface ProjectManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ProjectManager * _Nonnull shared;)
+ (ProjectManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull defaultProjectCollectionName;)
+ (NSString * _Nonnull)defaultProjectCollectionName SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, strong) ProjectRepository * _Nonnull local;
@property (nonatomic, strong) ProjectRepository * _Nonnull iCloud;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (Project * _Nullable)projectWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasProjectWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
- (ProjectCollection * _Nullable)collectionWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
- (ProjectCollection * _Nullable)collectionForProject:(Project * _Nonnull)project SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, strong) Project * _Nonnull defaultProjectTemplate;
@property (nonatomic, readonly, copy) NSArray<Project *> * _Nonnull templateProjects;
- (BOOL)saveProject:(Project * _Nonnull)project SWIFT_WARN_UNUSED_RESULT;
- (void)embedDependenciesIntoProject:(Project * _Nonnull)project;
@end


@interface ProjectManager (SWIFT_EXTENSION(RuntimeKit))
- (void)createCollectionWithName:(NSString * _Nonnull)name completion:(void (^ _Nonnull)(ProjectCollection * _Nullable, NSError * _Nullable))completion;
@end

@class UIColor;

@interface ProjectManager (SWIFT_EXTENSION(RuntimeKit))
+ (void)createProjectWithName:(NSString * _Nonnull)name withProjectString:(NSString * _Nonnull)projectString in:(ProjectCollection * _Nonnull)collection tintColor:(UIColor * _Nullable)tintColor completion:(void (^ _Nonnull)(Project * _Nullable, NSError * _Nullable))completion;
+ (void)createProjectWithName:(NSString * _Nonnull)name withTemplate:(Project * _Nonnull)template_ in:(ProjectCollection * _Nonnull)collection tintColor:(UIColor * _Nullable)tintColor completion:(void (^ _Nonnull)(Project * _Nullable, NSError * _Nullable))completion;
@end



@interface ProjectManager (SWIFT_EXTENSION(RuntimeKit))
- (NSArray<Project *> * _Nonnull)sortedDependentProjectsForProject:(Project * _Nonnull)project shouldFix:(BOOL)fix SWIFT_WARN_UNUSED_RESULT;
- (NSSet<Project *> * _Nonnull)allDependentProjectsForProject:(Project * _Nonnull)project shouldFix:(BOOL)fix SWIFT_WARN_UNUSED_RESULT;
- (NSSet<Project *> * _Nonnull)allDependentProjectsForProject:(Project * _Nonnull)project shouldFix:(BOOL)fix dependencies:(NSSet<Project *> * _Nonnull)dependencies SWIFT_WARN_UNUSED_RESULT;
@end


/// Monitors a local directory on the file system and creates
/// project collections for each subdirectory
/// This also creates a project collection representing the top-
/// level directory
SWIFT_RESILIENT_CLASS("_TtC10RuntimeKit17ProjectRepository")
@interface ProjectRepository : DirectoryMonitor <ProjectCollectionDelegate>
@property (nonatomic, readonly, copy) NSArray<ProjectCollection *> * _Nonnull collections;
- (void)projectCollection:(ProjectCollection * _Nonnull)collection removedProject:(Project * _Nonnull)project at:(NSInteger)index;
- (void)projectCollection:(ProjectCollection * _Nonnull)collection insertedProject:(Project * _Nonnull)project at:(NSInteger)index;
- (void)projectCollection:(ProjectCollection * _Nonnull)collection modifiedProject:(Project * _Nonnull)project at:(NSInteger)index;
- (void)reloadProjectCollection:(ProjectCollection * _Nonnull)collection;
- (nonnull instancetype)initWithUrl:(NSURL * _Nullable)url monitorForUpdates:(BOOL)monitorForUpdates skipHiddenFiles:(BOOL)skipHiddenFiles OBJC_DESIGNATED_INITIALIZER;
@end


@class UIFont;

SWIFT_CLASS("_TtC10RuntimeKit12RuntimeStyle")
@interface RuntimeStyle : NSObject
+ (UIFont * _Nonnull)codeFontWithSize:(CGFloat)size weight:(UIFontWeight)weight SWIFT_WARN_UNUSED_RESULT;
+ (UIFont * _Nonnull)codeFontForTextStyle:(UIFontTextStyle _Nonnull)textStyle weight:(UIFontWeight)weight SWIFT_WARN_UNUSED_RESULT;
+ (UIFont * _Nonnull)defaultFontWithSize:(CGFloat)size weight:(UIFontWeight)weight SWIFT_WARN_UNUSED_RESULT;
+ (UIFont * _Nonnull)preferredFontForTextStyle:(UIFontTextStyle _Nonnull)textStyle weight:(UIFontWeight)weight SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIFont * _Nonnull sidebarTitleFont;)
+ (UIFont * _Nonnull)sidebarTitleFont SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIFont * _Nonnull parameterTitleFont;)
+ (UIFont * _Nonnull)parameterTitleFont SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIFont * _Nonnull parameterValueFont;)
+ (UIFont * _Nonnull)parameterValueFont SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIFont * _Nonnull parameterActionFont;)
+ (UIFont * _Nonnull)parameterActionFont SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIFont * _Nonnull parameterTextFont;)
+ (UIFont * _Nonnull)parameterTextFont SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIFont * _Nonnull capturePanelTitleFont;)
+ (UIFont * _Nonnull)capturePanelTitleFont SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIApplication (SWIFT_EXTENSION(RuntimeKit))
- (UIViewController * _Nullable)viewControllerFor:(CodeaLuaState * _Nonnull)luaState SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC10RuntimeKit11WifiAddress")
@interface WifiAddress : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable current;)
+ (NSString * _Nullable)current SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
